(function(){function i(){function c(e,h){switch(b){case 0:(e===1?f:g).push(h);break;case e:h(d)}}function a(e,h){b=e;d=h;(e==1?f:g).forEach(function(o){o.apply(o,d)});g=f=null}var b=0,d,f=[],g=[],l,k;l={d:function(e){k.d(e);return this},h:function(e){k.h(e);return this}};return k={d:function(e){c(1,e);return this},h:function(e){c(2,e);return this},a:function(){var e=Array.prototype.slice.call(arguments);a(1,e);return l},e:function(){var e=Array.prototype.slice.call(arguments);a(2,e);return l},status:function(){return b},
q:function(){return l}}}function j(c){function a(k,e,h){g=g&&h;f[e]=k;d-=1;if(0===d)if(l)g?b.a.call(b.a,f):b.e.call(b.e,f);else g?b.a.apply(b.a,f):b.e.apply(b.e,f)}var b=i(),d=0,f=[],g=true,l;if(Array.isArray(c))l=true;else c=Array.prototype.slice.call(arguments);d=c.length;c.forEach(function(k,e){f.push(undefined);k.d(function(h){a(h,e,true)});k.h(function(h){a(h,e,false)})});return b}var m,n,p;function q(c,a){return function(){return c.apply(a,arguments)}}var r=Array.prototype.slice,s=Object.prototype.hasOwnProperty;
function t(c,a){function b(){this.constructor=c}for(var d in a)if(s.call(a,d))c[d]=a[d];b.prototype=a.prototype;c.prototype=new b;c.m=a.prototype}
m=function(){function c(a){this.p=0;this.f=new WebSocket(a);this.f.onopen=q(function(){return this.onopen()},this);this.f.onmessage=q(function(b){return this.onmessage(b)},this);this.k={}}c.prototype.onopen=function(){};c.prototype.onmessage=function(a){var b,d;b=JSON.parse(a.data);a=b.id;d=b.result;b=b.error;if(b!=null){this.close();throw Error(b["class"]+": "+b.message);}return this.k[a].a(d)};c.prototype.close=function(){return this.f.close()};c.prototype.send=function(a,b,d,f){this.k[a.id]=a.c;
return this.f.send(JSON.stringify({id:a.id,receiver:b,method:d,args:f}))};return c}();
n=function(){function c(a){this.b=a;this.id=this.b.p++;this.c=i();this.c.d(q(function(b){this.value=b;if(this.i)return this.i(b)},this))}c.prototype.send=function(){var a,b;b=arguments[0];a=2<=arguments.length?r.call(arguments,1):[];return this.l(b,a)};c.prototype.l=function(a,b){return this.j(b,q(function(d){return this.b.send(d,this.value,a,b)},this))};c.prototype.o=function(a){return this.i=a};c.prototype.g=function(a){var b,d,f,g;d=[];if(Array.isArray(a)){f=0;for(g=a.length;f<g;f++){b=a[f];d=
d.concat(this.g(b))}}else if(a.constructor===c)d.push(a.c);else if(a.constructor===Object)for(b in a){f=a[b];d=d.concat(this.g(f))}return d};c.prototype.j=function(a,b){var d;d=new c(this.b);j(this.g(a).concat(this.c)).d(function(){return b(d)});return d};c.prototype.toJSON=function(){if(this.value==null)throw Error("Object not complete");return this.value};return c}();
p=function(){function c(a){this.b=a;c.m.constructor.apply(this,arguments);this.b.onopen=q(function(){return this.c.a(null)},this)}t(c,n);c.prototype.close=function(){return this.b.close()};c.prototype.object=function(a){return this.j(a,q(function(b){return b.c.a(a)},this))};return c}();p.n=function(c){return new p(new m(c))};window.Brocket=p;p.connect=p.n;p.prototype.close=p.prototype.close;p.prototype.object=p.prototype.object;n.prototype.send=n.prototype.send;n.prototype.returned=n.prototype.o;
n.prototype.__noSuchMethod__=n.prototype.l;})()
