/* Copyright 2010-2011 Rolf Timmermans */
(function(){var g=null;
function h(){function c(f,j){switch(b){case 0:(f===1?e:i).push(j);break;case f:j(d)}}function a(f,j){b=f;d=j;(f==1?e:i).forEach(function(p){p.apply(p,d)});i=e=g}var b=0,d,e=[],i=[],n,m;n={i:function(f){m.i(f);return this},k:function(f){m.k(f);return this}};return m={i:function(f){c(1,f);return this},k:function(f){c(2,f);return this},e:function(){var f=Array.prototype.slice.call(arguments);a(1,f);return n},f:function(){var f=Array.prototype.slice.call(arguments);a(2,f);return n},status:function(){return b},M:function(){return n}}}
function k(c){function a(m,f,j){i=i&&j;e[f]=m;d-=1;if(0===d)if(n)i?b.e.call(b.e,e):b.f.call(b.f,e);else i?b.e.apply(b.e,e):b.f.apply(b.f,e)}var b=h(),d=0,e=[],i=true,n;if(Array.isArray(c))n=true;else c=Array.prototype.slice.call(arguments);d=c.length;c.forEach(function(m,f){e.push(undefined);m.i(function(j){a(j,f,true)});m.k(function(j){a(j,f,false)})});return b}var l,o,q;function r(c,a){return function(){return c.apply(a,arguments)}}var s=Array.prototype.slice,t=Object.prototype.hasOwnProperty;
function u(c,a){function b(){this.constructor=c}for(var d in a)if(t.call(a,d))c[d]=a[d];b.prototype=a.prototype;c.prototype=new b;c.F=a.prototype}
l=function(){function c(a){this.J=a;this.l=0;this.q={}}c.prototype.onmessage=function(a){var b,d;b=JSON.parse(a.data);a=b.id;d=b.result;b=b.error;return b!=g?this.q[a].f(b):this.q[a].e(d)};c.prototype.b=function(a){this.g=new WebSocket(this.J);this.g.onopen=function(){return a.e(g)};this.g.onerror=function(){return a.f(g)};this.g.onclose=function(){return a.f(g)};return this.g.onmessage=r(function(b){return this.onmessage(b)},this)};c.prototype.close=function(){return this.g.close()};c.prototype.h=
function(){return this.g.readyState===1};c.prototype.send=function(a,b,d,e){this.q[a.id]=a.d;return this.g.send(JSON.stringify({id:a.id,receiver:b,method:d,args:e}))};return c}();
o=function(){function c(a){this.a=a;this.id=this.a.l++;this.w()}c.prototype.send=function(){var a,b;b=arguments[0];a=2<=arguments.length?s.call(arguments,1):[];return this.C(b,a)};c.prototype.C=function(a,b){return this.v(b,r(function(d){return this.a.send(d,this.value,a,b)},this))};c.prototype.r=function(a){return this.j=a};c.prototype.o=function(a){var b,d,e,i;d=[];if(Array.isArray(a)){e=0;for(i=a.length;e<i;e++){b=a[e];d=d.concat(this.o(b))}}else if(a.constructor===c)d.push(a.d);else if(a.constructor===
Object)for(b in a){e=a[b];d=d.concat(this.o(e))}return d};c.prototype.v=function(a,b){var d;d=new c(this.a);k(this.o(a).concat(this.d)).i(function(){return b(d)});return d};c.prototype.w=function(){this.d=h();this.d.i(r(function(a){this.value=a;if(this.j)return this.j(this)},this));this.d.k(r(function(a){this.error=a;if(this.j)return this.j(this)},this))};c.prototype.toString=function(){var a;return(a=this.value)!=g&&a._ref?"[object "+(this.value._class||"(Class)")+":"+this.value._ref+">":JSON.stringify(this.value)};
c.prototype.toJSON=function(){if(this.value==g)throw Error("Object not complete");return this.value};return c}();q=function(){function c(a){this.a=a;c.F.constructor.apply(this,arguments);this.a.b(this.d)}u(c,o);c.prototype.b=function(){this.w();this.a.b(this.d);return this};c.prototype.close=function(){return this.a.close()};c.prototype.h=function(){return this.a.h()};c.prototype.object=function(a){return this.v(a,r(function(b){return b.d.e(a)},this))};return c}();q.b=function(c){return new q(new l(c))};
window.WebRocket=q;q.connect=q.b;q.prototype.connect=q.prototype.b;q.prototype.close=q.prototype.close;q.prototype.connected=q.prototype.h;q.prototype.object=q.prototype.object;o.prototype.send=o.prototype.send;o.prototype.returned=o.prototype.r;o.prototype.toJSON=o.prototype.toJSON;o.prototype.__noSuchMethod__=o.prototype.C;var v;r=function(c,a){return function(){return c.apply(a,arguments)}};
v=function(){function c(a){document.addEventListener("DOMContentLoaded",r(function(){this.element=a!=g?document.getElementById(a):document.body;this.m=WebRocket.b("ws://localhost:9003");this.H();return this.element.parentElement.addEventListener("click",r(function(){return this.p()},this))},this),false)}c.prototype.H=function(){this.c=this.l=0;this.history=[];this.element.innerHTML='<div class="console"><div id="console-messages" class="console-messages"></div><div class="console-tail"><div id="console-prompt" spellcheck="false" class="source-code console-prompt"></div></div></div>';
this.A=document.getElementById("console-messages");this.prompt=document.getElementById("console-prompt");this.prompt.addEventListener("keypress",r(function(a){return this.L(a)},this),false);this.prompt.addEventListener("keydown",r(function(a){return this.K(a)},this),false);this.p()};c.prototype.I=function(a){var b;this.z=g;this.c=++this.l;this.history.push(a);b=document.createElement("div");b.setAttribute("class","source-code console-command");b.appendChild(document.createTextNode(a));a=document.createElement("div");
a.setAttribute("class","console-group");a.appendChild(b);this.A.appendChild(a);window.scrollTo(0,document.body.scrollHeight);return a};c.prototype.p=function(){var a,b;this.prompt.setAttribute("contenteditable",true);this.prompt.focus();a=document.createRange();a.setStart(this.prompt,this.prompt.childNodes.length);a.setEnd(this.prompt,this.prompt.childNodes.length);b=window.getSelection();b.removeAllRanges();return b.addRange(a)};c.prototype.D=function(a){this.prompt.textContent=a;return this.p()};
c.prototype.u=function(){return this.D("")};c.prototype.G=function(){this.A.innerHTML=""};c.prototype.B=function(a){if(this.c===this.l)this.z=this.prompt.textContent;this.c+=a;if(this.c<0)this.c=0;if(this.c>this.history.length)this.c=this.history.length;this.D(this.history[this.c]||this.z)};c.prototype.K=function(a){var b;b=false;switch(a.keyCode){case 27:this.G();this.u();break;case 38:this.B(-1);break;case 40:this.B(+1);break;default:b=true}if(!b)return a.preventDefault()};c.prototype.L=function(a){if(a.keyCode===
13){a.preventDefault();this.exec(this.prompt.textContent);return this.u()}};c.prototype.exec=function(a){var b;if(a!==""){b=this.I(a);this.m.h()||this.m.b().r(r(function(){return this.m.h()?this.n(b,"Reconnected, your session may be lost"):this.n(b,"Could not connect")},this));return a==="?"?this.t(b,["WRB v0.1. Copyright 2010-"+(new Date).getFullYear()+" Rolf Timmermans.","Type any Ruby expression and press [Enter] to evaluate.\nPress [Esc] to clear the buffer."].join("\n")):this.m.send("eval",a).r(r(function(d){return d.error?
this.n(b,d.error["class"]+": "+d.error.message):this.t(b,d.value)},this))}};c.prototype.t=function(a,b){return this.s(a,b,"console-result")};c.prototype.n=function(a,b){return this.s(a,b,"console-error")};c.prototype.s=function(a,b,d){var e;e=document.createElement("div");e.setAttribute("class","source-code "+d);e.appendChild(document.createTextNode(b.replace(/\\n/g,"\n")));a.appendChild(e);return window.scrollTo(0,document.body.scrollHeight)};return c}();window.WRB=v;})()
