# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brocket}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rolf Timmermans"]
  s.date = %q{2011-04-18}
  s.default_executable = %q{wrb}
  s.description = %q{A Remote Method Invocation or Remote Procedure Call server for Ruby. Call Ruby methods from within your browser, using a WebSocket-based RPC client.}
  s.email = %q{r.timmermans@voormedia.com}
  s.executables = ["wrb"]
  s.files = [
    "Rakefile",
    "VERSION",
    "bin/wrb",
    "brocket.gemspec",
    "js/brocket.js",
    "js/src/brocket.coffee",
    "js/src/brocket.js",
    "js/src/console.coffee",
    "js/src/console.js",
    "js/src/externs.js",
    "js/src/futures.js",
    "lib/brocket.rb",
    "lib/brocket/connection.rb",
    "lib/brocket/dispatcher.rb",
    "lib/brocket/server.rb",
    "lib/brocket/tcp_socket/connection.rb",
    "lib/brocket/tcp_socket/listener.rb",
    "lib/brocket/tcp_socket/server.rb",
    "lib/brocket/tcp_socket/socket.rb",
    "lib/brocket/web_socket/connection.rb",
    "lib/brocket/web_socket/server.rb",
    "lib/brocket/wrb.rb",
    "prompt/index.html",
    "prompt/userInputIcon.png",
    "prompt/userInputPreviousIcon.png"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{WebSocket-based RPC server for Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

